#!/usr/bin/env python3
"""
VectraSim Intelligent Simulation Suite
AI-Generated JAX-Fluids Script - Mission Critical

Generated for: external_flow (3D)
Simulation Intent: Final complete test with all fixes applied - aerospace propeller
Plotting Mode: advanced

This script was automatically generated by VectraSim's AI agent
based on JAX-Fluids (Apache 2.0 licensed) for computational fluid dynamics.

VectraSim - Advanced Computational Physics Platform
"""

import os
import sys
import time
import json
import traceback

from jaxfluids import InputManager, InitializationManager, SimulationManager

def modify_config_for_production(case_file: str) -> str:
    """Apply VectraSim's proven optimizations for stable JAX-Fluids execution"""
    
    print("🔧 Applying VectraSim optimizations...")
    
    # Load original config
    with open(case_file, 'r', encoding='utf-8') as f:
        case_config = json.load(f)
    
    # VectraSim's proven optimizations
    # Disable levelset output to avoid JAX-Fluids output writing bug
    case_config['output'] = {
        "primitives": [],     # Minimal output for stability
        "miscellaneous": [], 
        "levelset": []        # Disable levelset output (avoids known JAX-Fluids bug)
    }
    
    # Ensure single device decomposition
    if 'domain' in case_config and 'decomposition' in case_config['domain']:
        case_config['domain']['decomposition'] = {
            'split_x': 1,
            'split_y': 1, 
            'split_z': 1
        }
    
    # Add gravity if missing (required by JAX-Fluids)
    if 'forcings' not in case_config:
        case_config['forcings'] = {'gravity': [0.0, 0.0, 0.0]}
    
    # Write optimized config
    optimized_file = case_file.replace('.json', '_ai_optimized.json')
    with open(optimized_file, 'w', encoding='utf-8') as f:
        json.dump(case_config, f, indent=2)
    
    print(f"✅ VectraSim AI optimizations applied: {os.path.basename(optimized_file)}")
    return optimized_file

def main():
    """Main function to execute the JAX-Fluids simulation."""
    
    start_time = time.time()
    
    case_file = "jaxfluids_external_flow_1753655497.json"
    numerical_file = "numerical_setup.json"
    
    try:
        # Apply VectraSim optimizations
        optimized_case_file = modify_config_for_production(case_file)
        
        # Initialize InputManager
        input_manager = InputManager(optimized_case_file, numerical_file)
        
        # Initialize InitializationManager
        initialization_manager = InitializationManager(input_manager)
        state = initialization_manager.initialize()
        
        # Initialize SimulationManager
        simulation_manager = SimulationManager(input_manager)
        
        # Run the simulation
        final_state = simulation_manager.simulate(state)
        
        end_time = time.time()
        simulation_time = end_time - start_time
        
        print(f"🚀 Simulation completed successfully in {simulation_time:.2f} seconds.")
        
        # Performance Metrics
        num_steps = input_manager.numerical_setup['time_stepping']['num_steps']
        print(f"📊 Performance: {simulation_time / num_steps:.4f} seconds per step.")
        
        # Clean up temporary files
        try:
            os.remove(optimized_case_file)
            print(f"🧹 Cleaned up temporary file: {os.path.basename(optimized_case_file)}")
        except OSError as e:
            print(f"⚠️ Warning: Could not remove temporary file {optimized_case_file}: {e}")
        
        sys.exit(0)  # Exit with success code
        
    except Exception as e:
        print(f"❌ Simulation failed: {e}")
        traceback.print_exc()
        
        # Clean up temporary files (attempt even on failure)
        try:
            if 'optimized_case_file' in locals():
                os.remove(optimized_case_file)
                print(f"🧹 Cleaned up temporary file: {os.path.basename(optimized_case_file)}")
        except OSError as cleanup_e:
            print(f"⚠️ Warning: Could not remove temporary file {optimized_case_file}: {cleanup_e}")
        
        sys.exit(1)  # Exit with error code

if __name__ == "__main__":
    main()